version: '2.4'

services:
  
  backend:
    build:
      context: ./../
      dockerfile: ./deployments/golang.dockerfile
    container_name: backend_uri-one
    command: make run_back
    depends_on:
      frontend:
        condition: service_healthy
    volumes:
      - ./../:/app

  frontend:
    build:
      context: ./../
      dockerfile: ./deployments/node.dockerfile
    container_name: frontend_uri-one
    command: make run_front
    volumes:
      - ./../:/app

networks:
  default:
    name: develop_net
