name: "DEB Build Ubuntu"

on:
  push:
    tags:
      - "*"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

#      - name: "Set up NodeJS"
#        uses: actions/setup-node@v2
#        with:
#          node-version: 14.15.4
#
#      - name: "Frontend build"
#        run: make build_font

      - name: "Set up Go"
        uses: actions/setup-go@v2
        with:
          go-version: 1.17

      - name: "Go tools install"
        run: |
          go install github.com/deweppro/go-static/cmd/static@latest
          go install github.com/mailru/easyjson/easyjson@latest
          go install github.com/dewep-online/deb-builder/cmd/deb-builder@latest
      - name: "Backend build"
        run: make build_back

      - name: "Deb build"
        run: deb-builder build --base-dir=${{ github.workspace }}/deb --tmp-dir=/tmp/deb

      - name: Upload deb files to a GitHub release
        uses: svenstaro/upload-release-action@2.2.1
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: ${{ github.workspace }}/deb/u/uri-one/*.deb
          tag: ${{ github.ref }}
          overwrite: true
          file_glob: true

      - name: Upload binary files to a GitHub release
        uses: svenstaro/upload-release-action@2.2.1
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: ${{ github.workspace }}/build/bin/uri-one_*
          tag: ${{ github.ref }}
          overwrite: true
          file_glob: true
